const { sumar } = require("./sumar")
const { resta } = require("./restar")
const { multiplicacion } = require("./multiplicacion")
const { dividir } = require("./dividir")
const { exponenciar } = require("./exponenciar")
const { modulo } = require("./modulo")

const resultado = sumar(5, 7)
const resultado2 = resta(10, 5)
const resultado3 = multiplicacion(5, 5)
const resultado4 = dividir(10, 2)
const resultado5 = exponenciar(2, 2)
const resultado6 = modulo(10, 2)

console.log(resultado)
console.log(resultado2)
console.log(resultado3)
console.log(resultado4)
console.log(resultado5)
console.log(resultado6)